# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tell_me_what_to_do' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'StitchSDK', '~> 6.0.0'
  # Pods for tell_me_what_to_do

  target 'tell_me_what_to_doTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tell_me_what_to_doUITests' do
    # Pods for testing
  end

end
